### ISSUE TITLE
migrate pandoc action example repo (this) to pandoc org

### ISSUE THREAD

**Issue by maxheld83** [pandoc/pandoc-action-example#1]
would increase visibility; and anyway, the hard work is done by @tarleb and @svenevs

**Comment by maxheld83** [comment]
@tarleb @svenevs I'd be happy to migrate these examples over to your pandoc org; I think that would be good for visibility.
I'll continue to maintain it.

**Comment by tarleb** [comment]
I think that'd be very cool. Cc @jgm

**Comment by maxheld83** [comment]
thanks for the invite @tarleb; could we instead **migrate** this repo over to the pandoc org?

Otherwise, I have to fix all the links in various places. (GitHub will automatically forward the URLS if the repo is migrated).

**Comment by tarleb** [comment]
oh, I see. Sure, let's do that. What's the easiest way to do so?

**Comment by maxheld83** [comment]
two ways:

1. I get repo create privileges on `pandoc`.
2. I make you admin of this repo (probably easier). Will do in a sec.

**Comment by maxheld83** [comment]
this is the button:

<img width="1068" alt="transfer" src="https://user-images.githubusercontent.com/5372770/71314126-288d9e80-2443-11ea-9035-854e5c414b41.png">

docs: https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by maxheld83** [comment]
oh ok, so I need (temporarily) privileges to be allowed to create repos on `pandoc` (not admin rights or anything more, just rights to create repos).
Then I can migrate my personal repo to the org.

Sorry about the hassle.

**Comment by tarleb** [comment]
I don't have permissions to do that. Cc @jgm.

**Comment by maxheld83** [comment]
I *could* transfer the repo to your personal account @tarleb, and then you transfer it over to the `pandoc` org, since *you* do have repo create privileges.
Let me know if you'd want that.

**Comment by tarleb** [comment]
ok, let's try that route

**Comment by maxheld83** [comment]
requested.

**Comment by maxheld83** [comment]
you might have to delete the "old", copied repo on `pandoc` first, otherwise there might be a naming conflict.

**Comment by tarleb** [comment]
Granting you permissions again, then we should be done. Glad this worked :+1:

**Comment by maxheld83** [comment]
great, I have write privileges on the repo (just tried), that's all I'd ever need I think.
Thanks!

**Comment by tarleb** [comment]
Great! Interestingly, I only have read permissions. :man_shrugging:
