### ISSUE TITLE
Deprecated functionality in github action

### ISSUE THREAD

**Issue by stephlocke** [pandoc/pandoc-action-example#12]
This error just came up when running the Advanced Usage GH workflow during a PR:
>Error: Unable to process command '::set-env name=FILELIST::"README.md" "lorem_1.md" "lorem_2.md" ' successfully.
> Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

https://github.com/stephlocke/pandoc-action-example/runs/1491442419

**Comment by carceneaux** [comment]
I found a [similar issue](https://github.com/actions/toolkit/issues/641) raised in the GitHub Action Toolkit itself. Contained there was the answer so I tested this in my fork and just submitted a PR.

**Comment by AlexHedley** [comment]
Thanks, the update to `echo "FILELIST=$(printf '"%s" ' *.md)" >> $GITHUB_ENV` worked great.
