### ISSUE TITLE
Reference r-lib's action to setup pandoc

### ISSUE THREAD

**Issue by pawamoy** [pandoc/pandoc-action-example#32]
When Pandoc is used in a subprocess, one cannot simply use the examples given in the README.
Instead, one should install Pandoc and make it globally available on the system. The README does not currently show how to do that.

My suggestion is to reference this action, [r-lib/setup-pandoc](https://github.com/r-lib/actions/tree/v2-branch/setup-pandoc), in the README, or maybe develop something similar. The mentioned action seems to work on Linux, Mac OS and Windows in GHA.

**Comment by tarleb** [comment]
Apologies for the late reply. This seems like a good suggestion, would you like to open a PR for this? Please also checkout the [pandoc/actions/setup](https://github.com/pandoc/actions/tree/main/setup) action. It's less complete than the r-lib action, but might also suit your needs.

**Comment by pawamoy** [comment]
No worries, thanks for your answer. Yep, I can open a PR mentioning both actions (didn't find the second one while searching! good to know it exists)
