### ISSUE TITLE
Add support for pandoc-include

### ISSUE THREAD

**Issue by AmitMY** [pandoc/pandoc-action-example#9]
I would like to include files under my main file.

I want to use:
https://hackage.haskell.org/package/pandoc-include

But it seems like its not working with these actions.

Is there a way to add `pandoc-include` so including files would work?
This is a really basic feature I'm surprised its not in pandoc core.

**Comment by florian6973** [comment]
I am very interested in this feature too!
Currently, I use conda and pip to install pandoc and pandoc-include and use it with github action but it is not optimized...

**Comment by tarleb** [comment]
My suggestion would be to use the [include-files Lua filter](https://github.com/pandoc/lua-filters/tree/master/include-files) instead. It doesn't require compilation and should serve as a full replacement.

**Comment by florian6973** [comment]
Thank for your advice. To do so, I would need to download the filter and put it in the repository? However, I believe there will be problems with the links to the bibliography, the csl style or images (I didn't succeed to set path, or it doesn't work for pandoc), and I don't see in the examples of this repo how to exclude a file (readme). My current script is (after installation of the dependencies : texlive, texlive-lang-french, pandoc, pandoc-include):
```bash
all_files=$(find $GITHUB_WORKSPACE -type f -name "*.md")
files_array=($(echo $all_files | tr ' ' "\n"))
for index in ${!files_array[*]}
do  
  f_path=${files_array[$index]}  
  dossier=$(dirname $f_path)
  nom_complet=$(basename $f_path)
  nom="${nom_complet%.*}"
  
  if [ $nom != "README" ]
  then  
    cd $dossier
    mkdir -p Bibliographie
    cp -n $GITHUB_WORKSPACE/Bibliographie/apa.csl Bibliographie/apa.csl
    pandoc --from markdown --to latex --filter /usr/share/miniconda/lib/python3.8/site-packages/pandoc_include.py -C $nom.md -o $GITHUB_WORKSPACE/$nom.pdf --metadata-file=$GITHUB_WORKSPACE/conf.yaml
    cd $GITHUB_WORKSPACE
  else
    echo "Ignoré"
  fi
done
```
Thank you :)

**Comment by tarleb** [comment]
I'm not quite sure what you are asking. Could you post this to the [pandoc-discuss mailing list](https://groups.google.com/forum/#!forum/pandoc-discuss)? There are more people who might be able to help.

Support for the requested Haskell filter is out-of-scope, so I'm closing this. Adding the official Lua filters to the Docker image would be worthwhile. I'm keeping it in mind. You can also open an issue in the pandoc/dockerfiles repo to gather more feedback.
